{{- if .Values.ingress.enabled }}
apiVersion: {{ template "network.apiVersion" . }}
kind: IngressClass
metadata:
  name: {{ template "dubbo.name" . }}
  annotations:
    {{ template "traefik.ingressclass.annotations" . }}
spec:
  controller: dubbo.io/ingress-controller
{{- end -}}
