apiVersion: install.dubbo.io/v1alpha1
kind: DubboOperator
metadata:
  namespace: dubbo-system
spec:
  components:
    base:
      enabled: true
  values:
    global:
      dubboNamespace: dubbo-system
